### ISSUE TITLE
GUI code attempts to launch sudo

### ISSUE THREAD

**Issue by fredsonnenwald** [volcanotech-sw/PyCamPermanent#262]
When launching the GUI under Linux I got a sudo prompt to enter my password to run commands as root that I was not at all expecting. I know the GUI is not listed as supporting Linux, but I believe this could also be happen if the the GUI is launched from the Windows Subsystem for Linux (WSL) on a Windows PC. Depending on the WSL configuration, these sudo commands could be running silently in the background with unintended consequences.

The sudo commands come from the `FTPClient` used by the GUI looking for the SSD mount location (`mount_path`) on the Pi, and doing this by running the `StorageMount` code designed run to manage the SSD on the Pi.

As `mount_path` is not part of any configuration file, and is not set anywhere other than in the intialisation of `StorageMount` I suggest changing `mount_path` into a class property that `FTPClient` can access without initialising `StorageMount` and thereby avoid calling on sudo.

Stack trace:
```
$ python run_pycam.py 
/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/controllers.py:30: UserWarning: Working on machine without seabreeze, functionality of some classes will be lost
  warnings.warn(
/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/controllers.py:38: UserWarning: Working on machine without Picamera2, functionality of some classes will be lost
  warnings.warn(
[sudo] password for fcs: 
Traceback (most recent call last):
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/run_pycam.py", line 1, in <module>
    from pycam.gui.pycam_gui import run_GUI
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/gui/pycam_gui.py", line 14, in <module>
    from pycam.gui.menu import PyMenu
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/gui/menu.py", line 5, in <module>
    from pycam.gui.network import ConnectionGUI, instrument_cmd, run_pycam
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/gui/network.py", line 5, in <module>
    import pycam.gui.cfg as cfg
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/gui/cfg.py", line 9, in <module>
    from pycam.networking.FTP import FTPClient, CurrentDirectories
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/networking/FTP.py", line 299, in <module>
    class FTPClient:
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/networking/FTP.py", line 308, in FTPClient
    def __init__(self, img_dir, spec_dir, network_info=None, storage_mount=StorageMount()):
                                                                           ^^^^^^^^^^^^^^
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/utils.py", line 353, in __init__
    self.find_dev()
  File "/home/fcs/Desktop/work/volcanoes/PyCamPermanent/pycam/utils.py", line 373, in find_dev
    stdout_value = proc.communicate()[0]
                   ^^^^^^^^^^^^^^^^^^
  File "/home/fcs/apps/miniconda3/envs/pycam/lib/python3.11/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
sudo: a password is required
```

**Comment by fredsonnenwald** [comment]
Changed code would be

utils.py:
```python
class StorageMount:
    mount_path = '/mnt/pycam/'
    def __init__(self, mount_path=None, dev_path=None):
        if mount_path:
            self.mount_path = mount_path
```
FTP.py:
```python
class FTPClient:
    def __init__(self, img_dir, spec_dir, network_info=None, storage_mount=StorageMount.mount_path):
```
and then replacing `self.storage_mount.data_path` with `self.storage_mount`.

**Comment by fredsonnenwald** [comment]
gui/cfg.py:
```python
ftp_client = FTPClient(img_dir=current_dir_img, spec_dir=current_dir_spec, network_info=config,
                       storage_mount=StorageMount.mount_path)
```

**Comment by twVolc** [comment]
Fixed by #269
