### ISSUE TITLE
Plume Velocity settings window doesn't open if ICA line is removed

### ISSUE THREAD

**Issue by twVolc** [volcanotech-sw/PyCamPermanent#266]
I'm loading a config file where the ICA line used for automative `flow_nadeau` orientation is set as the 3rd line. If I then remove that line (i.e. delete it from the SO2 image in the analysis window) and try to open the Plume Velocity Settings, the frame won't load and I get the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\gg1tcw\.conda\envs\pycam\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamPermanent\pycam\gui\figures_analysis.py", line 5710, in generate_frame
    self.nadeau_flow.generate_frame(self.windows)
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamPermanent\pycam\gui\figures_analysis.py", line 4789, in generate_frame
    self.run_nadeau_line()
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamPermanent\pycam\gui\figures_analysis.py", line 4965, in run_nadeau_line
    self.update_pcs_line(draw=False)
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamPermanent\pycam\gui\figures_analysis.py", line 4992, in update_pcs_line
    self.pcs_line_plot = self.ax_nad.plot([line.x0, line.x1], [line.y0, line.y1], 'c-')
AttributeError: 'NoneType' object has no attribute 'x0'
```

I think if this happens, i.e. the frame is looking for a line that no longer exists, it should just revert back to the first ICA line.

**Comment by ubdbra001** [comment]
Would you be able to include the PCS line file and copy your config so I can have a go recreating this?

**Comment by twVolc** [comment]
I think the easiest way to recreate this is doing it manually rather than me giving you a config file with everything that can be loaded correctly. Simplest way to recreate is the following:
1. Open Plume Velocity Settings
2. Go to Nadeau flow tab
3. Tick Automatic Line Generation and have the line set to 2. 
4. Close the window, go back to the Analysis window and shift Num ICAs to 1 (this should delete line 2)
5. Open up Plume velocity Settings again and this will fail with the above error as the line that Nadeau flow is trying to use doesn't exist

**Comment by ubdbra001** [comment]
Perfect, thanks! Will give it a go.

**Comment by ubdbra001** [comment]
> I think if this happens, i.e. the frame is looking for a line that no longer exists, it should just revert back to the first ICA line.

Just to check my understanding:
 - There should always be at least one ICA line? (if no, what should it do if there are no lines set?)
 - If the line set for automatic line generation is removed, then it should revert to the ICA line set at the lowest value (i.e. ICA 1)
   - Should this happen when the line is removed, and therefore the automatic line is regenerated immediately?
   - Or should it happen when the Plume Velocity Settings window is reopened?

**Comment by twVolc** [comment]
Yes, it shouldn't be possible to have 0 lines. The Analysis window prevents the num ICAs to drop below 1. So as you say, I think if the ICA line is removed the Flow Nadeau section should revert to ICA 1 being its line for automatic generation.

**Comment by ubdbra001** [comment]
Okay, that makes sense.
Looks like this will have to be done when the line is removed, as it is possible to start a processing run after removing the line and it will throw an error (because the line no longer exists), which I presume is not ideal.
Would probably also be good to include a warning here so the user knows that the autogenerated line has been changed.

Also, it looks like the spinbox goes above the actual number of lines that have been set (I think the upper limit is set as the length of the array including the `None`s)

**Comment by ubdbra001** [comment]
Okay, I think I have both sorted.
For the warning, would you like it to be written to the console/log as well as in a warning box?

**Comment by twVolc** [comment]
Brilliant.

I guess with GUI-less running in mind, these could conceivably be encountered when trying to load a config that has that auto line set to a higher value than the number of lines loaded by that config, so in this case it would make sense to put it into a log as well? For the GUI it's definitely useful to have it pop up as a warning box so the user is immediately aware.

Does that make sense?

**Comment by ubdbra001** [comment]
This is all done in the GUI code, so would not affect GUI-less running.

> load a config that has that auto line set to a higher value than the number of lines loaded by that config

I think this would need to be added as a validation rule in the code that loads the config file. I can do that, but it is a slightly separate issue.

**Comment by twVolc** [comment]
Ok, no problem for now. It's an extreme edge case and not worth worrying about for the time being.
